(function(){
var d=document,r=d.documentElement,s;
try{s=localStorage.getItem('th')}catch(e){}
r.dataset.theme=s||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
var SV='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">';
var MOON=SV+'<path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>',SUN=SV+'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>';
var MAIL='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></svg>';
var LI='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M4.98 3.5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5zM3 9.5h4V21H3zM9.5 9.5h3.8v1.6h.1c.5-1 1.8-1.9 3.7-1.9 4 0 4.7 2.6 4.7 6V21h-4v-5c0-1.2 0-2.7-1.7-2.7s-1.9 1.3-1.9 2.6V21h-4z"/></svg>';
function cu(el){var n=+el.dataset.n,dc=+el.dataset.d||0,sf=el.dataset.s||'',t0=null;function f(t){if(!t0)t0=t;var p=Math.min((t-t0)/1100,1);el.textContent=(n*(1-Math.pow(1-p,3))).toFixed(dc)+sf;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
var TL=["SQL","Python","R","Excel","Tableau","Power BI","Alteryx","Databricks","Snowflake","Claude","Cursor","LangChain","Gephi","Visio"];
function mg(h){return '<span class="mg"'+(h?' aria-hidden="true"':'')+'>'+TL.map(function(t){return '<i>'+t+'</i>'}).join('')+'</span>'}
var MQ='<div class="mq" role="group" aria-label="Tools I use"><div class="mt">'+mg(0)+mg(1)+'</div></div>';
function rot(){var el=d.querySelector('.rw');if(!el||matchMedia('(prefers-reduced-motion:reduce)').matches)return;var ws=["messy data","competitor landscapes","pricing questions","customer reviews"],i=0;setInterval(function(){el.classList.add('out');setTimeout(function(){i=(i+1)%ws.length;el.textContent=ws[i];el.classList.remove('out')},300)},2800)}
var P=[
["Sep 2026","Teaching AI When to Ask a Human","Messy customer records waste a sales team's time. I built a workflow where AI sorts them and only the questionable ones reach a person, cutting manual checks from about 100 rows to about 20.",["Claude","Excel","Data Quality"],"Automated a Claude and Excel CRM data-cleaning workflow that routes ambiguous, invalid, and duplicate records to human review. Built an Excel rule-based cross-check against Claude's classifications that surfaced 6 disagreements on a 46-row synthetic test, exposing gaps in the prompt and rules. Stress-tested across three identical runs and a minimal-rules prompt: consistent labels, zero false-positive leads, and a missing business rule."],
["Aug 2026","What 5,000 Smartwatch Reviews Are Really Saying","A star rating says whether people like a product, not why. I used code to read about 5,000 reviews and sort them into 5 themes customers keep bringing up.",["Python","NLTK","TextBlob","LDA"],"Wrote all of the code and built every chart. Preprocessed review text with NLTK, scored sentiment across about 5,000 reviews with TextBlob, and used LDA topic modeling to surface 5 themes, with word clouds to visualize them."],
["Jul 2026","Why the Cereal Aisle Loves a Good Display","Do in-store displays actually move product? Branded cereal sold up to 410% more on display, versus 144% for store brands.",["Excel","Python","Data Validation"],"Validated a 524,950-row retail dataset, then analyzed 170,000+ transactions in Python, comparing unit sales lift from display for branded manufacturers (up to 410%) against private label (144%)."],
["Jun 2026","Where Did the Ad Dollars Go?","Companies spend across Google, Meta, and TikTok without knowing which pays off. I showed Google returns $2.10 for every $1 spent.",["Excel","Regression","Hypothesis Testing"],"Built an Excel framework unifying Google, Meta, and TikTok Ads data. Regression derived spend multipliers, such as $2.10 returned per $1 on Google, validated at p &lt; 0.05."],
["Apr 2026","The 80/20 Hunt","Where does a platform's money really come from? The top 20% of categories drove 80% of revenue.",["SQL","Claude","Pareto Distribution"],"Modeled 100k+ SQLite transaction records for a Pareto distribution analysis, using Claude to refactor subquery logic. The top 20% of categories drove 80% of platform revenue."],
["Apr 2026","How Fast Does a Car Lose Its Value?","Cars lose value at different speeds depending on who's buying. I mapped depreciation across borrowers' credit tiers.",["SQL","Tableau Prep","Excel"],"Engineered a SQL database joining 50k+ VIN, transaction, and rate records, then used window functions to isolate depreciation curves across credit tiers, surfaced in an interactive Tableau dashboard."],
["Apr 2026","Who Knows Whom in Tech?","Relationships hide inside long articles. I had AI read about 10 tech leaders and map who connects to whom.",["Python","LangChain","Groq API","Gephi"],"Used LangChain and the Groq API to extract entity relationships from unstructured Wikipedia text on 10 tech leaders, then built the network in Gephi and ran modularity and community detection to surface clusters and connector nodes."],
["Mar 2026","Where the Profit Hides","Sales numbers can hide what's really costing or earning money. I found two shipping-cost outliers and the 10 most profitable customers.",["Tableau"],"Joined fragmented relational data in Tableau across six visualizations, surfacing two shipping-cost outliers and the top 10 customers by profit to guide discount strategy."],
["Mar 2026","Farm Country, Side by Side","Which parts of the country grow the most, and how do they compare? I lined up crop yields across top states and counties from 1981 to 1985.",["Tableau","Data Storytelling"],"Built small-multiples visualizations in Tableau comparing average crop yield across top producing states and counties (1981 to 1985), then assembled them into a Tableau story using logical rhetoric."],
["Feb 2026","Flight Paths and Traffic Jams","Where do airline networks get congested, and which design is riskier? I mapped 200+ routes to find out.",["Tableau","Spatial Analysis"],"Built an interactive Tableau network visualization across 200+ routes for major carriers, using spatial functions to isolate peak congestion and compare hub-and-spoke versus point-to-point risk."],
["Jan 2026","Does Your Driving Predict Your Claims?","Insurers want to know who's likely to file a claim. I tested whether habits like hard braking give it away.",["Python","Pandas","Scikit-Learn"],"Cleaned driving-behavior data modeled after the Progressive Snapshot program and built risk scoring models in Python to correlate habits like hard braking with claims likelihood."],
["Jan 2026","Buying Smarter","Purchasing is one of the easiest places to quietly lose money. I redesigned a $5M process, projecting 14% faster cycles and 20% less risk.",["Excel","Visio"],"Mapped a Source-to-Pay workflow for a $5M procurement category and built a Supplier Risk dashboard for 12 vendors, projecting a 14% cycle-time cut and 20% lower risk exposure."],
["Oct 2025","Six Hours, One Trophy","A national data competition with a six-hour clock. My team took 1st place and cut projected travel spend 15%.",["Alteryx","Power BI","PowerPoint"],"Led a team in the Alteryx and RSM Datathon, blending a 75,000-row flight dataset with a 3,580-row roster to cut projected travel spend 15% and transit hours 18%."],
["Sep 2025","A News Feed That Knows You","Most news apps show everyone the same thing. I built one that personalizes the feed, with zero ingestion errors.",["Python","Next.js 15","Base44","Vercel"],"Used Cursor AI to accelerate a full-stack Next.js 15 build and engineered async Python pipelines for unstructured news data, with zero ingestion errors and a 95+ Lighthouse score."],
["Mar to May 2025","The Blueprint Behind Campus Data","A university's student data is only useful if it's organized so you can ask it questions. I designed the blueprint for a campus database that answers things like which international students have high GPAs.",["SQL","MySQL","MongoDB","ER Modeling"],"Designed the ER diagram for an academic analytics database and normalized it to Third Normal Form. Wrote SQL queries to pull insights, including international students above a GPA threshold and majors ranked by enrollment count."]];
function card(p){return '<button class="c" aria-pressed="false" aria-label="'+p[1]+'. Flip for details"><span class="in"><span class="fr"><small class="dt">'+p[0]+'</small><b class="ti">'+p[1]+'</b><span class="sub">'+p[2]+'</span><span class="ts">'+p[3].map(function(t){return '<i class="t">'+t+'</i>'}).join('')+'</span><small class="hint">Click to flip for details</small></span><span class="bk"><small class="dt">What I did</small><span class="sub">'+p[4]+'</span><small class="hint">Click to flip back</small></span></span></button>'}
var E=[
["Aug 2026 to present","Lead GTM Strategist Intern","Resilient Privacy","Built a scored competitive matrix across 7+ ITSM/IT-ops vendors and designed a competitor classification framework to sharpen platform differentiation ahead of launch."],
["Feb 2026 to May 2026","Data Analyst Intern","UT Dallas Basic Needs Resource Center","Unified 3,000+ rows of student sign-in data and built interactive Tableau heatmaps, cutting leadership's report-generation time by 40%."],
["Jan 2026 to May 2026","Business Analyst &amp; Team Lead","Verbalytics","Led a 5-member analyst team through a 16-week engagement, building a Go-To-Market strategy and TAM/SAM/SOM sizing for a B2B healthcare SaaS startup, earning 100% executive buy-in."],
["Jan 2026 to Mar 2026","Private Equity Intern","Project Destined","Conducted commercial real estate financial analysis and valuation modeling, then pitched a property acquisition strategy to a panel of industry executives."],
["Jun 2025 to Feb 2026","Student Assistant","UT Dallas Basic Needs Resource Center","Represented the center at campus events and supported engagement initiatives connecting students with resources."],
["Aug 2025 to Oct 2025","Digital Product AI Strategy Extern","News Corp","Analyzed behavior data from 750+ surveys and built an A/B testing framework across onboarding flows, benchmarking 8 competitors into 6 recommendations for executives."],
["Aug 2024 to Jan 2025","Data Management Intern","Avishkar Technology","Designed SQL-based ETL pipelines automating daily Snowflake loads of 10k+ rows at 99%+ accuracy and built Power BI dashboards that cut manual processing time by 25%."]];
function sec(t,b,c){return '<section class="sec '+(c||'')+'"><div class="w"><h2>'+t+'</h2>'+b+'</div></section>'}
function cols(a){return '<div class="cols">'+a.map(function(x){return '<div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div>'}).join('')+'</div>'}
var pg=d.body?0:0;
function render(){
var b=d.body,k=b.dataset.page,m=d.getElementById('m'),h='';
var nav=[["index.html","Home","home"],["about.html","About","about"],["projects.html","Projects","projects"],["experience.html","Experience","experience"],["resume.html","Resume","resume"],["contact.html","Contact","contact"]];
var LG=k=='home'?'<a class="logo" href="index.html">YN</a>':'<a class="logo" href="index.html" aria-label="Home"><img class="av" src="profile.jpg" alt="Yugandhari Narayanam"></a>';b.insertAdjacentHTML('afterbegin','<header class="hd"><div class="w">'+LG+'<nav class="nav" aria-label="Main">'+nav.map(function(n){return '<a href="'+n[0]+'"'+(n[2]==k?' class="on" aria-current="page"':'')+'>'+n[1]+'</a>'}).join('')+'</nav><button class="tg" id="tg"></button></div></header>');
if(k=='home'){h='<section class="w hero"><div><p class="mu">Business analytics &amp; AI graduate, open to relocate</p><h1>I help companies bring their ideas to market.</h1><p class="lead">I love digging into <span class="rw">messy data</span>, building models, and figuring out the smartest next move for a launch or a big decision.</p><p class="st"><span class="dot"></span>Open to full-time roles</p><a class="btn p" href="projects.html">View projects</a><a class="btn" href="contact.html">Get in touch</a></div><img class="me" src="profile.jpg" alt="Yugandhari Narayanam"></section><div class="w stats"><div><b data-n="3.67" data-d="2">3.67</b><span>GPA, Cum Laude</span></div><div><b data-n="15">15</b><span>Projects built</span></div><div><b data-n="524" data-s="K+">524K+</b><span>Rows validated in one project</span></div></div>'+MQ+sec('Recent projects','<div class="g">'+P.slice(0,3).map(card).join('')+'</div><p><a class="btn p" href="projects.html">See all 15 projects</a></p>','pj')}
if(k=='about'){h='<div class="w pg"><h1>About</h1><p class="lead">UT Dallas Business Analytics &amp; AI graduate, Cum Laude. I build the dashboards, pricing models, and go-to-market work behind a real decision, and explain why it is the right one.</p></div>'+sec('Skills',cols([["Data and analysis","SQL, Python, R, Excel (VBA, DAX), ETL/ELT, A/B testing, statistical testing"],["Visualization and tools","Tableau, Power BI, Alteryx, Databricks, Visio, Claude"],["Business acumen","Market sizing (TAM/SAM/SOM), competitive intelligence, go-to-market strategy, risk management, stakeholder communication"]]))+sec('Certifications','<ul class="l"><li>Strategic and Analytical Skills in CPG Selling</li><li>Pinterest MMM Reporting</li><li>AI for Marketing</li><li>Claude 101</li><li>AI/BI for Data Analysts (Databricks)</li><li>Databricks Fundamentals</li><li>Computational Social Science Methods</li><li>Emotional and Social Intelligence</li><li>Data Analyst in Python</li><li>McKinsey Forward Program</li><li>Big Data, Artificial Intelligence, and Ethics</li><li>Accounting Analysis I (Coursera)</li><li>Fundamentals of Financial and Management Accounting (Coursera)</li></ul>')+sec('Education','<div class="cols"><div><h3>The University of Texas at Dallas</h3><p>B.S. Business Analytics &amp; AI, Finance &amp; Risk Analytics Concentration, Cum Laude. GPA 3.67, Jan 2024 to May 2026.</p></div><div><h3>Collin Community College</h3><p>Associate of Arts, Business, Cum Laude. GPA 3.8, Aug 2022 to May 2024. Dean&#39;s List and President&#39;s List.</p></div></div>')+sec('Leadership and activities','<ul class="l"><li>Transfer Mentor, Transfer Mentor Program (Aug 2025 to May 2026)</li><li>Emcee, Telugu Student Association (Sep 2025 to May 2026)</li><li>Marketing Manager, Business Professionals of America (Apr 2025 to Jan 2026)</li></ul><p class="mu">Selected to represent UT Dallas at the NASPA Strategies Conference in Chicago as a Transfer Mentor.</p>')}
if(k=='projects'){h='<div class="pj"><div class="w pg"><h1>Projects</h1><p class="lead mu">Click any card to see what I did and how.</p><br><div class="g">'+P.map(card).join('')+'</div></div></div>'}
if(k=='experience'){h='<div class="w pg"><h1>Experience</h1>'+E.map(function(e){return '<div class="tl"><small>'+e[0]+'</small><h3>'+e[1]+', '+e[2]+'</h3><p class="mu">'+e[3]+'</p></div>'}).join('')+'</div>'}
if(k=='resume'){h='<div class="w pg"><h1>Resume</h1><a class="btn p" href="resume.pdf" download>Download PDF</a><object data="resume.pdf" type="application/pdf" aria-label="Resume PDF"><p>Your browser cannot show the PDF. <a href="resume.pdf">Open it directly</a>.</p></object></div>'}
if(k=='contact'){h='<div class="w pg"><h1>Let\'s talk about a role</h1><p class="lead">Open to full-time opportunities anywhere in the U.S. Best way to reach me is email. I will get back within a day or two.</p><div class="ics"><a class="ic" href="mailto:narayanamyugandhari@gmail.com">'+MAIL+'<span>narayanamyugandhari@gmail.com</span></a><a class="ic" href="https://www.linkedin.com/in/yugandharilakshmi">'+LI+'<span>linkedin.com/in/yugandharilakshmi</span></a></div></div>'}
m.innerHTML=h;rot();var sb=d.querySelectorAll('.stats b');if(sb.length&&window.IntersectionObserver&&!matchMedia('(prefers-reduced-motion:reduce)').matches){var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){cu(e.target);io.unobserve(e.target)}})});sb.forEach(function(x){io.observe(x)})}
b.insertAdjacentHTML('beforeend','<footer class="ft"><div class="w"><div><b>Explore</b>'+nav.map(function(n){return '<a href="'+n[0]+'">'+n[1]+'</a>'}).join('')+'</div><div><b>Connect</b><a href="mailto:narayanamyugandhari@gmail.com">Email</a><a href="https://www.linkedin.com/in/yugandharilakshmi">LinkedIn</a></div></div></footer>');
var tb=d.getElementById('tg');function tl(){var dk=r.dataset.theme=='dark';tb.innerHTML=(dk?SUN+' Light mode':MOON+' Dark mode');tb.setAttribute('aria-label',dk?'Switch to light mode':'Switch to dark mode')}tl();tb.onclick=function(){var t=r.dataset.theme=='dark'?'light':'dark';r.dataset.theme=t;try{localStorage.setItem('th',t)}catch(e){}tl()};
d.addEventListener('click',function(e){var c=e.target.closest('.c');if(c){c.classList.toggle('f');c.setAttribute('aria-pressed',c.classList.contains('f'))}})}
d.addEventListener('DOMContentLoaded',render)})();
